name: cpplint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cpplint
      - name: Linting
        run: |
          cpplint \
            --repository=. \
            --recursive \
            --filter=-whitespace/line_length,-whitespace/braces,-whitespace/parens,-whitespace/comments,-whitespace/end_of_line,-legal/copyright,-whitespace/blank_line,-readability/braces,-whitespace/indent,-build/include,-runtime/references \
            .
